# Generated by Django 3.2 on 2021-04-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='website_link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
