# Generated by Django 3.2 on 2021-04-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='website_link',
            field=models.URLField(max_length=255),
        ),
    ]
