# Generated by Django 3.2 on 2021-04-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='website_link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
